package threads.server;

public enum Message {
    CONNECT, SHARE, REPLY,
    SESSION_CALL, SESSION_ACCEPT, SESSION_BUSY,
    SESSION_REJECT, SESSION_OFFER,
    SESSION_ANSWER, SESSION_CANDIDATE, SESSION_CLOSE
}
