package threads.server;

public enum Message {
    CONNECT, CONNECT_REPLY, SHARE, REPLY,
    SESSION_CALL, SESSION_ACCEPT, SESSION_BUSY,
    SESSION_REJECT, SESSION_OFFER, SESSION_TIMEOUT,
    SESSION_ANSWER, SESSION_CANDIDATE,
    SESSION_CLOSE, SESSION_CANDIDATE_REMOVE
}
